name = "vantage"
description = "A minimal theme for the Vantage Framework documentation"
license = "MIT"
homepage = "https://vantage-framework.rs"
min_version = "0.17.0"
demo = ""

[author]
name = "Vantage"
homepage = "https://vantage-framework.rs"

[original]
author = "Vantage"
homepage = "https://vantage-framework.rs"
repo = ""

[extra]
