# The URL the site will be built for
base_url = "https://vantage-framework.rs"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "dracula"
# When set to "true", missing highlight languages are treated as errors
error_on_missing_highlight = false
# Insert anchor links for headers
# insert_anchor_links = "left"

[extra]
# Put all your custom variables here
