# The URL the site will be built for
base_url = "https://romaninsh.github.io/vantage-web/"

# The theme to use
theme = "vantage"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to minify the html output
minify_html = false

# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true



[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
# Insert anchor links next to headings
insert_anchor_links = "right"

[extra]
# Put all your custom variables here
